# Test Cases – Flavora

| Test Type     | TC ID   | Test Case                              | Steps                                      | Expected Result                                                                 | Actual Result                                                                 |
|---------------|--------|----------------------------------------|--------------------------------------------|----------------------------------------------------------------------------------|--------------------------------------------------------------------------------|
| Functional    | TC-01  | Ana səhifə açılması                   | URL daxil et                               | Səhifə errorsuz açılmalıdır, blank page olmamalıdır                             | Səhifə problemsiz açılır, məlumatlar düzgün əks olunur                        |
| Functional    | TC-02  | Button-ların yoxlanması               | Bütün button-lara klik et                  | Doğru action / redirect baş verməlidir                                          | Button-lar düzgün işləyir, sayt crash olmur                                  |
| Functional    | TC-03  | Form submit yoxlanması                | Formu doldur və submit et                 | Success / error mesajı göstərilməlidir                                           | Form dolu olduqda submit uğurludur                                           |
| UI/UX         | TC-05  | Layout və dizayn                     | Saytı aç                                  | Elementlər düzgün yerləşir, layout pozulmamalıdır                              | Səhifədə elementlər düzgün yerləşir, görünüş pozulmur                        |
| UI/UX         | TC-06  | Font və rəng                         | Sayt açıq vəziyyətdə                      | Font və rəng oxunaqlıdır, button dizayn istifadəçi üçün başa düşülən olmalıdır  | Font və rəng oxunaqlıdır, button dizayn istifadəçi üçün başa düşüləndir       |
| Responsive    | TC-08  | Mobil görünüş                        | Telefon ölçüsündə aç                      | Elementlər pozulmamalı, content düzgün görünməlidir                             | Mobil görünüş uyğundur                                                       |
| Responsive    | TC-09  | Tablet görünüş                       | Tablet ölçüsündə aç                       | Layout adaptiv işləməlidir                                                      | Tablet görünüş uyğundur                                                      |
| Responsive    | TC-10  | Desktop görünüş                      | Desktop cihazında aç                      | Bütün content düzgün görünməlidir                                               | Desktop görünüş uyğundur                                                     |
| Compatibility | TC-11  | Chrome brauzer                       | Saytı Chrome-da aç                        | Sayt düzgün açılmalı və işləməlidir                                             | Sayt açılır, error olmur                                                     |
| Compatibility | TC-12  | Firefox brauzer                      | Saytı Firefox-da aç                       | Sayt düzgün açılmalı və işləməlidir                                             | Sayt açılır, error olmur                                                     |
| Compatibility | TC-13  | Safari / Edge / OS                   | Müxtəlif brauzerlər və OS-lərdə aç        | Problem yoxdur                                                                  | Sayt açılır, error olmur                                                     |
| Exploratory   | TC-14  | Yanlış input / boş form              | Düzgün olmayan data daxil et, boş submit  | Validation error göstərilməlidir                                                | Validation error göstərir, sayt crash olmur                                  |
| Exploratory   | TC-15  | Random kliklər                       | Linkləri və elementləri təsadüfi kliklə   | Sayt düzgün cavab verməli, redirect və crash olmamalıdır                       | Sayt düzgün cavab verir, redirect və crash olmur                             |
| Functional    | TC-002 | Səhifənin yenilənməsi                | Refresh browser                           | Səhifə uğurla yenilənməlidir                                                   | Pass                                                                          |
| Functional    | TC-005 | İnvalid dəyişənlə submit yoxlanması  | Formanı boş saxla submit et               | Xəta mesajı göstərilməli və ya düzəliş tələb edilməlidir                       | Pass                                                                          |
| Functional    | TC-006 | Səhv emailin yoxlanması              | Yanlış email forması daxil et             | Xəta mesajı göstərilməli və ya düzəliş tələb edilməlidir                       | Pass                                                                          |
